spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/library
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo